FROM postgres:16-bookworm

COPY deploy/postgres_roles.sql /usr/local/share/cloudledger/postgres_roles.sql
COPY deploy/docker/postgres-init.sh /docker-entrypoint-initdb.d/20-cloudledger-roles.sh

RUN chmod 0644 /usr/local/share/cloudledger/postgres_roles.sql \
  && chmod 0555 /docker-entrypoint-initdb.d/20-cloudledger-roles.sh
