[package]
name = "cloudledger-server"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
axum.workspace = true
cloudledger-core.workspace = true
cloudledger-service.workspace = true
rand_core = { workspace = true, features = ["getrandom"] }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
subtle.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
toml.workspace = true
tower-http.workspace = true
uuid.workspace = true
